// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY9QGpqNepEJ54Z_UQgSvXz4CkFvX66sw',
    appId: '1:581849232596:web:497e726a5e5d8fe00ab741',
    messagingSenderId: '581849232596',
    projectId: 'airplane-4ec05',
    authDomain: 'airplane-4ec05.firebaseapp.com',
    storageBucket: 'airplane-4ec05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvY8Wz0GaZuL01YQqzO2M_b1fu5YnzFIM',
    appId: '1:581849232596:android:43db82f52aa47d360ab741',
    messagingSenderId: '581849232596',
    projectId: 'airplane-4ec05',
    storageBucket: 'airplane-4ec05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu0tbg-XaRQQRDp7zPB1caWDuPOy76rzw',
    appId: '1:581849232596:ios:3735061a45d1865f0ab741',
    messagingSenderId: '581849232596',
    projectId: 'airplane-4ec05',
    storageBucket: 'airplane-4ec05.appspot.com',
    iosClientId: '581849232596-3m2fjkj6e6esve098obq82h9icaahue8.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu0tbg-XaRQQRDp7zPB1caWDuPOy76rzw',
    appId: '1:581849232596:ios:3735061a45d1865f0ab741',
    messagingSenderId: '581849232596',
    projectId: 'airplane-4ec05',
    storageBucket: 'airplane-4ec05.appspot.com',
    iosClientId: '581849232596-3m2fjkj6e6esve098obq82h9icaahue8.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplane',
  );
}
